version: '2.8'

services:
  mongo-db:
    image: mongo:4.2.6
    restart: always
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
    - "27017"
      
# Mongo URI Connection:
# mongodb://root:root@server.local:27017/